config/routes.rb
Rails.application.routes.draw do
  resources :bicycles, only: [:show, :index] do
    get :commit, :on => :member
    get :like, :on => :member
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    post 'login', to: 'devise/sessions#create'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :user

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bicycles#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  belongs_to :category # , optional: true
  has_one :commit, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :pic,  dependent: :destroy
  has_many :liked_by, through: :likes, source: :user
  has_one :user, through: :commit

  validates :name, uniqueness: true, presence: true
  accepts_nested_attributes_for :pic

  include Filterable
  scope :category, -> (category_id) { where category_id: category_id }
  scope :user, -> (user_id) { joins(:liked_by).where(users: {id: user}) }
  scope :uncommitted, -> (user_id) { joins(:user).where.not(users: {id: user_id}) }

  before_save { name.downcase! if name } 

  def self.search(query)
    where('name LIKE ? OR description LIKE ?', "%#{query}%", "%#{query}%")
  end

  def self.search_uncommitted(committed_id, query)
    uncommitted(committed_id).search(query)
  end
  # than capitilise if needed or we can store original name in attribute 
  # like: attr_accessor :oname... oname = name; name.downcase!
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bicycles

  validates :name, uniqueness: true, presence: true
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :bicycle
  belongs_to :user

  validates_uniqueness_of :user_id, :bicycle_id
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :bicycle
  belongs_to :user

  validates :user_id, uniqueness: { scope: :bicycle_id }
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :bicycle, touch: true

  # Mount carrierwave picture uploader
  mount_uploader :image, PicUploader

  # Callbacks
  before_create :default_name

  # Returns the default name fo a picture
  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable #,:recoverable,

  has_many :likes, dependent: :destroy
  has_one :commit, dependent: :destroy
  has_one :bicycle, through: :commit
  has_many :liked, through: :likes, source: :bicycle

  alias_attribute :name, :email
  
  def liked?(id)
    liked.exists?(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # Everything of Pundit from my pundit learning project 
  # before_action :authorizes

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private
  def user_not_authorized
    # flash[:alert] = "You are not authorized to perform this action."
    raise if Rails.env.test?
    redirect_to (request.referrer || store_path), notice: "You are not authorized to perform this action."
  end

  protected
    def authorizes
      unless request.format == Mime::HTML
        authenticate_or_request_with_http_basic do |n, p|
          user = User.find_by_name(n)
          if user and user.authenticate(p)
            session[:user_id] = user.id
          end
        end
      else
        return if User.count.zero?

        unless User.find_by_id(session[:user_id])
          redirect_to login_url, notice: "Please log in" 
        end
      end
    end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_bicycle, only: [:show, :commit, :like]

  helper_method :sort_column, :sort_direction, :search_string, :permitted_params, :filter_by_options
  # GET /products
  # GET /products.json
  def index
    bicycles = Bicycle.search(params[:search])
    filtered = bicycles.filter(filtering_params(params)) # optimise search here
    @bicycles = filtered.includes(:pic, :category, :user, :likes).order(sort_column + " " + sort_direction).page(params[:page]).per(2)
    @filter_by = [:category_id]

    respond_to :html, :js
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  def commit
    commitment = @bicycle.user
    commitment == current_user ? 
      @bicycle.commit.delete
      : 
      @bicycle.user = current_user
    redirect_to @bicycle, notice: 'Bicycle commitment changed.'
  end

  def like
    @bicycle.liked_by.include?(current_user) ? 
      @bicycle.liked_by.delete(current_user)
      : 
      @bicycle.liked_by << current_user
    redirect_to @bicycle, notice: 'Your like have changed.'
  end
  
  private
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    def sort_column
      Bicycle.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def search_string
      params[:search]
    end

    def permitted_params
      params.permit(:sort, :direction, :page, :search, :utf8, category: [], user: [])
    end

    def filtering_params(params)
      # params.slice(:category, :user)
      params.slice(:category)
    end

    def filter_by_options(klass)
      filter = klass.singularize.classify.constantize
      filter.all.map {|c| [c.id, c.name]}    
    end

    def bicycle_params
      params.require(:bicycle).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
      attributes["class"] = "hidden"
    end
    content_tag("div", attributes, &block)
  end
  def filter_chbox_option(filter_name, filter_value)
    id = filter_name.to_s.singularize
    flag = (params[filter_name].include? filter_value.to_s) unless params[filter_name].nil?

    check_box_tag "#{filter_name}[]", filter_value, flag, {id: id }    
  end
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
  def sortable(column, name = nil)
    name ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to name, permitted_params.merge(sort: column, direction: direction, page: nil), {class: css_class, remote: true}
    # carries all parameters accross on link click (merges them with sort and direction params)
  end
end

app/views/bicycles/_bicycle.html.slim
div class="bike" 
  
  h2  = bicycle.name
  -if bicycle.pic
    = params[:action] == "show" ? image_tag(bicycle.pic.image.url) : image_tag(bicycle.pic.image.thumb.url)
  h3 Description:
  p = bicycle.description
  h3 Category:
  p = bicycle.category.name
  - if bicycle.user.nil? 

    - if user_signed_in?
      -if current_user.bicycle.nil?
        h3
          = link_to 'Commit', commit_bicycle_path(bicycle)
      -elsif current_user.bicycle != bicycle
        h3 Can't commit
        p You are already committed to another bike   
    - else
      h3 No one commited 
  -else
    h3 Commited by:
      #{bicycle.user.name}

    -if bicycle.user == current_user
      = link_to 'Uncommit', commit_bicycle_path(bicycle) 
  h3 
    | Likes: 
    = bicycle.likes.count
  
  - if user_signed_in?
    - unless bicycle.liked_by.include?(current_user) 
      h3
        = link_to 'Like', like_bicycle_path(bicycle)
    - else
      h3
        = link_to 'Dislike', like_bicycle_path(bicycle) 
       
  
  - unless params[:action] == "show"
    = link_to 'Show', bicycle  

app/views/bicycles/_filter.html.slim
nav#filter-bicycles.sidebar-item
  = form_tag bicycles_path, method: 'get', id:"filter-form", class: "filter form-horizontal", remote: true  do
    .form-group
      = hidden_field_tag :direction, params[:direction], {class: "f-direction"}
      = hidden_field_tag :sort, params[:sort], {class: "f-sort"}
      = hidden_field_tag :search, params[:search], {class: "f-search"}
      - @filter_by.each do |filter_by_sym|
        - filter_by = filter_by_sym.to_s.split('_')[0]
        h3 Filter by
        h4.category= filter_by.capitalize
        ul
          - filter_by_options(filter_by).each do |filter_item, filter_name|
            li
              = filter_chbox_option(filter_by, filter_item)
              <label class="light" for="filter_item"> #{filter_name}</label> 

    .form-group
      .col-sm-offset-4.col-sm-5
        = submit_tag 'submit', name: nil, id: "filter-submit"
        = javascript_tag "$('.filter #filter-submit').hide()"

app/views/bicycles/_list.html.slim
table.sorting
  tr
  	th Sort by:
    th= sortable "name"
    th= sortable "updated_at", "Released"

- if @bicycles.blank?
  h3 
    | There are no bikes satisfying search a query or a filter
- else
  = render partial: "bicycle", collection: @bicycles

= paginate @bicycles, remote: true

app/views/bicycles/bk_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicycles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.name %></td>
        <td><%= bicycle.description %></td>
        <td><%= link_to 'Show', bicycle %></td>
        <td><%= link_to 'Edit', edit_bicycle_path(bicycle) %></td>
        <td><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bicycle', new_bicycle_path %>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicycles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.name %></td>
        <td><%= bicycle.description %></td>
        <td><%= link_to 'Show', bicycle %></td>
        <td><%= link_to 'Edit', edit_bicycle_path(bicycle) %></td>
        <td><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bicycle', new_bicycle_path %>

app/views/bicycles/index.html.slim
p#notice =notice

= render 'filter'

div.bike-list
  h1 Bicycles
  =render 'list'

app/views/bicycles/index.js.erb
document.title = "<%= escape_javascript("Bugcycles: #{params[:search].to_s.titleize} Sorted by #{(params[:sort].blank? ? 'name' : params[:sort]).titleize} - Page #{params[:page] || 1}") %>";
// history.pushState(null, document.title, this.href);
$("input#sort, input.f-sort").val('<%=sort_column%>');
$("input#direction, input.f-direction").val('<%=sort_direction%>');
$("input#search, input.f-search").val('<%=search_string%>');
$(".bike-list").html("<%= escape_javascript(render("list")) %>");
// $("#filter-bicycles").html("<%= escape_javascript(render("filter")) %>");

app/views/bicycles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="bike-list">
  <%= render partial:'bicycle', locals: { bicycle: @bicycle } %>
</div>

app/views/layouts/_banner.html.slim
.banner
  .wrapper
    p Bugcycle search
    
    = form_tag bicycles_path, :method => 'get', id: 'search-frm', class: 'form-inline', remote: true do
      .form-group
        = hidden_field_tag :direction, params[:direction]
        = hidden_field_tag :sort, params[:sort]
        = text_field_tag :search, params[:search], class: "form-control"
        = submit_tag "Search", name: nil, class: "btn btn-primary"

app/views/layouts/_header.html.slim
nav#custom-bootstrap-menu.custom-bootstrap-menu.navbar.navbar-default.navbar-static-top role="navigation"
  .container  
    .navbar-header
      #logo.nav.navbar-nav 
        a.navbar-brand href="#{main_app.root_path}" 
          h1 Bugcycle
        p.navbar-text Buggy little site
      button.navbar-toggle.collapsed data-target=".navbar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        div.btn-menu
            dic.stripes
        / span.icon-bar
        / span.icon-bar
        / span.icon-bar
    .navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        li.nav-item
          = link_to "Home", root_path
        li.nav-item
          = link_to "Admin", admin_root_path
        li.nav-item
        - if current_user
          li.nav-item
            = link_to "Logged in as #{current_user.email}", logout_path, method: :delete
          li.nav-item
            = link_to "Log out", logout_path, method: :delete
        - else
          li.nav-item
            = link_to "Log in", login_path
          li.nav-item
            = link_to "Sign up", new_user_registration_path
        
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugcycle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>  
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
<html>
  <head>
    title  Bugcycle
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  </head>

  <body>
    = render "layouts/header"
    .container
      -if params[:action] == "index"
        = render 'layouts/banner'
      .content
        = yield
  </body>
</html>

app/views/layouts/bk_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugcycle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       
    <%= yield %>
  </body>
</html>